version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tinvel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tinvel_user
      POSTGRES_PASSWORD: tinvel_password
      POSTGRES_DB: tinvel_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: